In [3]:
import numpy as np

matris = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(matris)

print(matris.shape)  # (3, 3) matris

print(matris.ndim)  # dizinin kaç boyutlu old.

print(matris.size)  # dizideki eleman sayısı

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9


In [ ]:
dizi = np.array(
    [
        [
            [1,2],
            [3,4]
        ],
        [
            [5,6],
            [7,8]
        ]
    ]
)

print(dizi)

print(dizi.shape)  # 2 adet matris, her matriste 2 satır, 2 sütun

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [ ]:
dizi = np.arange(12)

print(dizi)

# matrise dönüştürme

matris = dizi.reshape(3,4)  # 3 satır, 4 sütun

print(matris)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
