In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.concatenate((a,b))

print(result)


[1 2 3 4 5 6]


In [ ]:
import numpy as np

a = np.array(
    [
        [1,2],
        [3,4]
    ]
)

b = np.array(
    [
        [5,6],
        [7,8]
    ]
)

result = np.concatenate((a,b))    # varsayılan olarak satır yönünde birleştirdi

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
import numpy as np

a = np.array(
    [
        [1,2],
        [3,4]
    ]
)

b = np.array(
    [
        [5,6],
        [7,8]
    ]
)

result = np.concatenate((a,b), axis = 0)    # satır yönü birleştirme

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
import numpy as np

a = np.array(
    [
        [1,2],
        [3,4]
    ]
)

b = np.array(
    [
        [5,6],
        [7,8]
    ]
)

result = np.concatenate((a,b), axis = 1)    # sütun yönü birleştirme

print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

a = np.array(
    [
        [1,2],
        [3,4]
    ]
)

b = np.array(
    [
        [5,6],
        [7,8]
    ]
)

result = np.vstack((a,b))     # vertical stack dikey birleştirme
                              # axis = 0 gibi 

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
import numpy as np

a = np.array(
    [
        [1,2],
        [3,4]
    ]
)

b = np.array(
    [
        [5,6],
        [7,8]
    ]
)

result = np.hstack((a,b))     # horizontal stack yatay birleştirme
                              # axis = 1 gibi 

print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
dizi = np.array([1,2,3,4,5,6])

result = np.split(dizi,2)       # bölünmeyen sayılarsa hata verir

print(result) 

[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
matris = np.array(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8]
    ]
)

result = np.split(matris, 2)      # satır bazında böldü

print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [13]:
matris = np.array(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8]
    ]
)

result = np.split(matris, 2, axis = 0)      # satır bazında böldü

print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [14]:
matris = np.array(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8]
    ]
)

result = np.split(matris, 2, axis = 1)      # sütun bazında böldü

print(result)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]
