In [5]:
import numpy as np

dizi = np.array([10,20,30,40,50])

print(dizi[0])
print(dizi[-1])

10
50


In [7]:
import numpy as np

dizi = np.array([10,20,30,40,50])

print(dizi[0:4])

[10 20 30 40]


In [8]:
import numpy as np

dizi = np.array([10,20,30,40,50])

print(dizi[:4])

[10 20 30 40]


In [10]:
import numpy as np

dizi = np.array([10,20,30,40,50])

print(dizi[2:])

[30 40 50]


In [11]:
import numpy as np

dizi = np.array([10,20,30,40,50])

print(dizi[::2])

[10 30 50]


In [18]:
import numpy as np

matris = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

print(matris)

print(matris[1][1])

print(matris[1])         # satır
print(matris[1, :])

print(matris[:, 2])      # sütun

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[4 5 6]
[4 5 6]
[3 6 9]


In [19]:
import numpy as np

matris = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

print(matris[0:2, 0:2])


[[1 2]
 [4 5]]
