In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result = a + b

print(result)

[5 7 9]


In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result = a - b

print(result)

[-3 -3 -3]


In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result = a * b

print(result)

[ 4 10 18]


In [3]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result = a / b

print(result)

[0.25 0.4  0.5 ]


In [4]:
import numpy as np

a = np.array([1,2,3])

result = a * 2

print(result)

[2 4 6]


In [5]:
import numpy as np

a = np.array([1,2,3])

result = a ** 2

print(result)

[1 4 9]


In [6]:
import numpy as np

a = np.array([1,2,3])

result = np.sqrt(a)

print(result)

[1.         1.41421356 1.73205081]


In [7]:
import numpy as np

a = np.array([1,2,3])

result = np.sum(a)

print(result)

6


In [10]:
import numpy as np

a = np.array([1,2,3,10,100])

result = np.mean(a)

print(result)

23.2


In [11]:
import numpy as np

a = np.array([1,2,3])

result = np.min(a)

print(result)

1


In [12]:
import numpy as np

a = np.array([1,2,3])

result = np.max(a)

print(result)

3


In [ ]:
import numpy as np

a = np.array([1,2,3,10,100])

result = np.std(a)      # standart sapma

print(result)

38.529988320787226
