In [5]:
import numpy as np

a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

print(a)
print(b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [6]:
# dot product

a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])


result = np.dot(a,b)

print(result)

[[19 22]
 [43 50]]


In [ ]:
# matris transpose

a = np.array([
    [1,2],
    [3,4]
])

print(a.T)     # a.T

[[1 3]
 [2 4]]


In [ ]:
# matris determinant

a = np.array([
    [1,2],
    [3,4]
])

det = np.linalg.det(a)

print(det)

-2.0000000000000004


In [10]:
# matris inverse

a = np.array([
    [1,2],
    [3,4]
])

inv = np.linalg.inv(a)

print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]
