In [ ]:
import numpy as np

# SORU 1
# 1) NumPy kullanarak 1’den 20’ye kadar sayılardan oluşan bir dizi oluşturun.
# 2) Dizinin kaç eleman içerdiğini ekrana yazdırın.

array = np.arange(1,21)
print(array.size)

20


In [2]:

# SORU 2
# 1) [5, 10, 15, 20, 25] değerlerinden oluşan bir NumPy dizisi oluşturun.
# 2) Dizideki tüm elemanları 3 ile çarpın.
# 3) Sonucu ekrana yazdırın.


array = np.array([5, 10, 15, 20, 25])

array = array * 3

print(array)

[15 30 45 60 75]


In [7]:
import numpy as np

# SORU 3
# 1) 0’dan 30’a kadar sayılar içeren bir dizi oluşturun.
# 2) Bu diziden sadece 10 ile 20 arasındaki elemanları slicing kullanarak seçin.


array = np.arange(0,31)

print(array[10:21])

[10 11 12 13 14 15 16 17 18 19 20]


In [8]:
# SORU 4
# 1) [1,2,3] ve [4,5,6] dizilerini oluşturun.
# 2) Bu iki diziyi NumPy kullanarak birleştirin.


a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.concatenate((a,b))
print(a,b)

[1 2 3] [4 5 6]


In [11]:
# SORU 5
# 1) 1’den 12’ye kadar sayılar içeren bir dizi oluşturun.
# 2) Bu diziyi reshape kullanarak 3x4 boyutunda bir matrise dönüştürün.
# 3) Matrisin shape değerini yazdırın.


array = np.arange(1,13)

matris = array.reshape((3,4))

print(matris.shape)

(3, 4)


In [13]:
# SORU 6
# 1) Aşağıdaki matrisi oluşturun
# [[1,2,3],
#  [4,5,6],
#  [7,8,9]]
# 2) İkinci satırı ekrana yazdırın.
# 3) İkinci sütunu ekrana yazdırın.


matris = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matris[1, :])

print(matris[:, 1])

[4 5 6]
[2 5 8]


In [16]:
# SORU 7
# 1) 3x3 boyutunda rastgele sayılardan oluşan bir matris oluşturun.
# 2) Matrisin ortalamasını hesaplayın.
# 3) Matrisin maksimum değerini yazdırın.


matris = np.random.rand(3,3)
mean = np.mean(matris)
max = np.max(matris)

print(f"matris: {matris}, ortalama: {mean}, max: {max}")


matris: [[0.05175675 0.10654671 0.10136735]
 [0.64365125 0.60007235 0.69831196]
 [0.32795721 0.40611591 0.58119979]], ortalama: 0.39077547544648, max: 0.6983119636387718


In [17]:
# SORU 8
# 1) [2,4,6,8] ve [1,3,5,7] dizilerini oluşturun.
# 2) Dizileri eleman bazlı çarpın.
# 3) Sonucu ekrana yazdırın.

a = np.array([2,4,6,8])
b = np.array([1,3,5,7])

result = a * b

print(result)

[ 2 12 30 56]


In [18]:
# SORU 9
# 1) 1’den 9’a kadar sayılar içeren bir dizi oluşturun.
# 2) Bu diziyi 3x3 matrise dönüştürün.
# 3) Matrisin transpose’unu hesaplayın.


array = np.arange(1,10)

matris = array.reshape(3,3)

print(matris)

print()

print(matris.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [19]:
# SORU 10
# 1) 1 ile 50 arasında rastgele 10 tam sayı üretin.
# 2) Bu sayılardan oluşan dizinin toplamını hesaplayın.
# 3) Dizinin ortalamasını yazdırın.

array = np.random.randint(1,50,10)

result = np.sum(array)
mean = np.mean(array)

print(f"dizi: {array}, toplam: {result}, ortalama: {mean}")

dizi: [ 1 16 18 32 33 28 36 17  9 15], toplam: 205, ortalama: 20.5
