In [ ]:
import numpy as np

random = np.random.rand(5)   # 0-1 arasında 5 sayı oluşturma

print(random)

[0.56962509 0.12981027 0.96813459 0.75078003 0.13925139]


In [ ]:
random = np.random.rand(3,3)   # 3x3 matris üretme

print(random)

[[0.88722557 0.75968581 0.28161307]
 [0.6899562  0.58262771 0.47844322]
 [0.41672982 0.59501559 0.01431919]]


In [ ]:
random = np.random.randint(1,10,5)  # 1-10 arasında 5 tane tamsayı üret

print(random)

[4 8 1 9 6]


In [ ]:
random = np.random.randint(1,20,(3,4))  # 1-20 arasında 3x4'lük matris üret

print(random)

[[ 7 13 14  2]
 [ 8 16  6 19]
 [13  1  3 13]]


In [ ]:
# aynı rastgele sonucu üretmek için

np.random.seed(42)    # bu atamayı yaptıktan sonra aynı inputa hep aynı outputu vericek
                      # seed'i değiştirdiğinde sonuçlar değişir ama 

random = np.random.rand(5)

print(random)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [ ]:
dizi = np.array([10,20,30,40,50])

choice = np.random.choice(dizi)      # diziden rasgele eleman seçer

print(choice)

10


In [ ]:
dizi = np.array([10,20,30,40,50])

choice = np.random.choice(dizi, 3)    # diziden 3 tane elemanı seçer

print(choice)

[30 30 20]
