In [ ]:
"""
numpy:  Yüksek performanslı sayısal hesaplar için
        büyük veri, hızlı mat, matris hesaplama
        numpy C dili ile yazılmış
        
"""

import numpy as np

"""
Diziler(Array)
    ndarray: n-dimensional array
"""

nums = [1,2,3,4,5]
print(nums)

nums_numpy = np.array(nums)
print(nums_numpy)

print(type(nums_numpy))

print(nums_numpy.shape)   # (5,) -> 5 elemanlı tek boyutlu dizi

print(nums_numpy.dtype)   # int64 -> integer
# numpy dizileri içerisinde tek çeşit veri tipi depolar


[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int64


In [6]:
dizi = np.zeros(5)

print(dizi)

[0. 0. 0. 0. 0.]


In [7]:
dizi = np.ones(5)

print(dizi)

[1. 1. 1. 1. 1.]


In [ ]:
dizi = np.arange(0,10)

print(dizi)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
dizi = np.arange(0, 10, 2)

print(dizi)

[0 2 4 6 8]


In [ ]:
dizi = np.linspace(0, 10, 5)    # [ 0.  2.5   5.  7.5  10. ]  0 ile 10 arasında 5 sayı üret

print(dizi)

[ 0.   2.5  5.   7.5 10. ]
